package Frontend.Lexer;


public enum SysYTokenType {
    // 标识符
    IDENTIFIER,
    
    // 常量
    INT_CONST, FLOAT_CONST,
    DEC_CONST, OCT_CONST, HEX_CONST,
    DEC_FLOAT, HEX_FLOAT,
    STRING_CONST,
    
    // 关键字
    CONST, INT, FLOAT, VOID,
    IF, ELSE, WHILE, BREAK, CONTINUE, RETURN,
    
    // 运算符
    PLUS, MINUS, MULTIPLY, DIVIDE, MODULO,
    LESS, GREATER, LESS_EQUAL, GREATER_EQUAL, EQUAL, NOT_EQUAL,
    LOGICAL_AND, LOGICAL_OR, LOGICAL_NOT,
    ASSIGN,
    
    // 分隔符
    SEMICOLON, COMMA,
    LEFT_PAREN, RIGHT_PAREN,
    LEFT_BRACKET, RIGHT_BRACKET,
    LEFT_BRACE, RIGHT_BRACE,
    
    EOF
} 